[book]
authors = ["jianxun-p <s4pan@uwaterloo.ca>"]
language = "en"
title = "Jianxun's Blog"
description = "Personal blog."
src = "src"

[build]
create-missing = false

[preprocessor.katex]
after = ["links"]

[output.html]
theme = "theme"
default-theme = "rust"
git-repository-url = "https://github.com/jianxun-p/jianxun-p.github.io"
git-repository-icon = "fa-github"
additional-js = ["js/scripts.js"]

[output.html.print]
enable = true
page-break = true
